# Generated by Django 5.2.8 on 2025-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(default='0000-0000', max_length=15),
            preserve_default=False,
        ),
    ]
